Hotel/Entities/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Entities
{
    public class Order
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public int RoomId { get; set; }
        public int FullPrice { get; set; }
        public bool Buyed { get; set; }
        public DateTime OrderTime { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public Room Room { get; set; }
        public User User { get; set; }
        public Statuses Statuses { get; set; }
    }
}

Hotel/Models/Order/AllOrdersViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Order
{
    public class AllOrdersViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool Buyed { get; set; }
        public int RoomId { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public Room Room { get; set; }
        public User User { get; set; }
        public Statuses Statuses { get; set; }
    }
}

Hotel/Models/Order/OrderHistoryViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Order
{
    public class OrderHistoryViewModel
    {
        public int Id { get; set; }
        public int FullPrice { get; set; }
        public DateTime OrderTime { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public Room Room { get; set; }

    }
}

Hotel/Models/Order/OrderViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Order
{
    public class OrderViewModel
    {
        public string Id { get; set; }

        [Display(Name = "Имя")]
        public string FirstName { get; set; }

        [Display(Name = "Фамилия")]
        public string LastName { get; set; }

        [Display(Name = "Отчество")]
        public string Patronymic { get; set; }

        [Display(Name = "Номер телефона")]
        public string PhoneNumber { get; set; }
        public int FullPrice { get; set; }
        public int RoomId { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }

        [Display(Name = "Дни")]
        public int Days { get; set; }

        public Statuses Statuses = Statuses.NotGiven;
    }
}

Hotel/Models/Order/ReservationInfoViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Order
{
    public class ReservationInfoViewModel
    {
        public DateTime InTime { get; set; }
        public DateTime OutTime { get; set; }
        public int RoomId { get; set; }
        public Room Room { get; set; }
        public Queue<DateTime> FirstMonth { get; set; }
        public Queue<DateTime> SecondtMonth { get; set; }
        public List<DateTime> AllOlders { get; set; }
    }
}

Hotel/Controllers/OrderController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Hotel.CalendarServices;
using Hotel.Data.Interface;
using Hotel.EmailServices;
using Hotel.Entities;
using Hotel.Models.Order;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Controllers
{
    public class OrderController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IOrderRepository _repositoryOrder;
        private readonly IRepository<Room> _roomRepository;
        private readonly IRepository<OrderHistory> _historyRepository;
        private readonly IRepository<Order> _repository;
        private readonly IMapper mapper;
        private readonly CalendarService _calendar;

        public OrderController(IOrderRepository repositoryOrder, UserManager<User> userManager, IRepository<Room> roomRepository, IRepository<OrderHistory> historyRepository,
            IMapper mapper, IRepository<Order> repository, CalendarService calendar)
        {
            _repositoryOrder = repositoryOrder;
            _userManager = userManager;
            _roomRepository = roomRepository;
            _historyRepository = historyRepository;
            this.mapper = mapper;
            _repository = repository;
            _calendar = calendar;
        }

        public async Task<IActionResult> ReservationInfo(int roomId)
        {
            if (!User.Identity.IsAuthenticated)
            {
                TempData["alert"] = "Необходимо войти в учетную запись или зарегистрироваться!";
                return RedirectToAction("AllRooms", "Home");
            }

            var user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            bool check = await _repositoryOrder.CheckOrderMyName(user.Email);

            if (!user.EmailConfirmed)
            {
                TempData["alert"] = "Email должна быть подтверждена!";
                return RedirectToAction("AllRooms", "Home");
            }
            else if (check)
            {
                TempData["alert"] = "Клиент может забронировать только один номер!";
                return RedirectToAction("AllRooms", "Home");

            }

            var room = await _roomRepository.GetAll()
            .Include(c => c.RoomCategory)
            .Where(x => x.Id == roomId)
            .FirstOrDefaultAsync();

            var allorders = await _repository.GetAll().Where(q => q.RoomId == roomId).ToListAsync();

            List<DateTime> rooms = new();
            foreach (var roomdays in allorders)
            {
                if (roomdays.OrderTime != DateTime.MinValue)
                {
                    for (var day = roomdays.CheckInTime; day.Date <= roomdays.CheckOutTime; day = day.AddDays(1))
                    {
                        rooms.Add(day.Date);
                    }
                }
            }

            var firstMonth = _calendar.GetFirstMonth();
            var secondtMonth = _calendar.GetSecondMonth();

            var rmodel = new ReservationInfoViewModel
            {
                Room = room,
                RoomId = roomId,
                FirstMonth = firstMonth,
                SecondtMonth = secondtMonth,
                AllOlders = rooms
            };

            ViewData["NameMonth"] = DateTime.Now.ToMonthName().ToUpper();
            ViewData["NameNextMonth"] = DateTime.Now.AddMonths(1).ToMonthName().ToUpper();
            ViewData["WeeksContFirstMonth"] = _calendar.WeeksCountFirstMonth();
            ViewData["WeeksContSecondMonth"] = _calendar.WeeksCountSecondMonth();

            return View(rmodel);

        }

        [HttpPost]
        public async Task<IActionResult> Reservation(ReservationInfoViewModel model, string returnUrl)
        {
            var user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            var time = model.OutTime - model.InTime;

            var room = await _roomRepository.GetAll()
                .Include(c => c.RoomCategory)
                .Where(x => x.Id == model.RoomId)
                .FirstOrDefaultAsync();

            var allolders = await _repository.GetAll().Where(q => q.RoomId == model.RoomId).ToListAsync();

            foreach (var roomdays in allolders)
            {
                for (var day = roomdays.CheckInTime; day.Date <= roomdays.CheckOutTime; day = day.AddDays(1))
                {
                    for (var realday = model.InTime; realday.Date <= model.OutTime; realday = realday.AddDays(1))
                    {
                        if (roomdays.OrderTime != DateTime.MinValue)
                        {
                            if (day.Date == realday.Date)
                            {
                                TempData["alert"] = "Комната не доступна в данный период, так как пересекаются с другими занятыми днями!";
                                return Redirect(returnUrl);
                            }
                        }
                    }
                }
            }

            int price = (int)(Convert.ToInt32(time.Days + 1) * room.RoomCategory.Price);

            var modelr = new OrderViewModel
            {
                RoomId = room.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Patronymic = user.Patronymic,
                PhoneNumber = user.PhoneNumber,
                Days = time.Days + 1,
                FullPrice = price,
                CheckInTime = model.InTime,
                CheckOutTime = model.OutTime
            };
            return View(modelr);
        }

        [HttpPost]
        public async Task<IActionResult> CompleteReservation(OrderViewModel model, bool editinfo = false)
        {
            var user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);

            await _repositoryOrder.AddOrderAsync(model, editinfo, user);

            var room = await _roomRepository.GetAll()
                .Include(k => k.RoomCategory)
                .Where(x => x.Id == model.RoomId)
                .FirstOrDefaultAsync();

            EmailService emailService = new EmailService();
            string message = $"Спасибо за заказ!" +
                $"Тип комнаты => {room.RoomCategory.Name}.\nЭтаж: {room.Floor}.\nЦена:{model.FullPrice} " +
                $"на {model.Days} сут. \nЗаезд:{model.CheckInTime.Date.ToString("dd/MM/yyyy")}. \nВыезд:{model.CheckOutTime.Date.ToString("dd/MM/yyyy")}. \nФамилия:{model.LastName}." +
                $"Имя:{model.FirstName}. Отчество:{model.Patronymic}.\nТелефон для связи:+74584798742. Адрес:г.Набережные Челны, проспект Сююмбике, д.2.\n Ждём вас снова!!!";
            await emailService.SendEmailAsync(user.Email, "Информация о заказе", message);

            return RedirectToAction("OrderHistoryMyName");
        }

        public async Task<IActionResult> OrderHistoryMyName()
        {
            var user = await _userManager.FindByNameAsync(HttpContext.User.Identity.Name);
            var orderHistory = await _historyRepository.GetAll()
                .Include(x => x.User)
                .Include(x => x.Room.RoomCategory)
                .Include(x => x.Room)
                .Where(x => x.User.Id == user.Id)
                .OrderByDescending(x => x.CheckInTime)
                .ProjectTo<OrderHistoryViewModel>(mapper.ConfigurationProvider)
                .ToListAsync();

            var actualroom = await _repository.GetAll().Include(x => x.Room.RoomCategory).Where(m => m.Email == user.Email && m.OrderTime != DateTime.MinValue).FirstOrDefaultAsync();

            if (actualroom != null)
            {
                var days = actualroom.CheckOutTime - actualroom.CheckInTime;
                ViewData["Name"] = actualroom.Room.RoomCategory.Name;
                ViewData["CheckInTime"] = actualroom.CheckInTime.ToString("dd/MM/yyyy");
                ViewData["CheckOutTime"] = actualroom.CheckOutTime.ToString("dd/MM/yyyy");
                ViewData["FullPrice"] = actualroom.FullPrice;
                ViewData["Days"] = days.Days + 1;
                ViewData["OrderId"] = actualroom.Id;
            }
            else
            {
                ViewData["Name"] = null;
            }

            return View(orderHistory);
        }


        public async Task<IActionResult> CancelMyOrder(int orderId)
        {
            var order = await _repository.GetByIdAsync(orderId);
            await _repository.RemoveAsync(order);

            return RedirectToAction("OrderHistoryMyName");
        }
    }
}

Hotel/Views/Order/CompleteOrder.cshtml
<div class="container">
    <h3>Заказ успешно сохранен!</h3>
    <h5>Оплата производится при получении комнаты!</h5>
</div>

<style>
    body {
        background: url(../img/banner2.jpg);
    }
</style>

Hotel/Views/Order/OrderHistoryMyName.cshtml
@model IEnumerable<Hotel.Models.Order.OrderHistoryViewModel>

<div class="container">
    <div>
        <fieldset>
            <legend><b>Забронированная комната</b></legend>
            @if (@ViewData["Name"] == null)
            {
                <div>
                    <h3>В настоящий момент у вас нет забронированных комнат</h3>
                </div>
            }
            else
            {
                <div>
                    <h3>Вид номера: @ViewData["Name"]</h3>
                    <p>Дата заезда: @ViewData["CheckInTime"]</p>
                    <p>Дата выезда: @ViewData["CheckOutTime"]</p>
                    <p>Цена: @ViewData["FullPrice"] на @ViewData["Days"] сут.</p>
                    <a class="btn btn-danger" asp-action="CancelMyOrder" asp-route-orderId="@ViewData["OrderId"]">Отменить</a>
                </div>
            }
        </fieldset>
    </div>

    <table class="table" id="customers">
        <caption>Все заказы</caption>
        <tr>
            <th>Вид номера</th>
            <th>Дата заезда</th>
            <th>Дата выезда</th>
            <th>Цена</th>
            <th></th>
        </tr>
        @foreach (var history in Model)
        {

            <tr>
                <td>
                    @history.Room.RoomCategory.Name
                </td>
                <td>
                    @history.CheckInTime.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @history.CheckOutTime.ToString("dd/MM/yyyy")
                </td>
                <td>
                    @history.FullPrice
                </td>
                <td>
                    <a class="btn btn-success" asp-controller="Order" asp-action="ReservationInfo" asp-route-roomId="@history.Room.Id">Повторить</a>
                </td>
            </tr>
        }
    </table>
</div>

<style>
    body {
        background: url(../img/banner2.jpg);
    }

    caption {
        font-family: 'Rock Salt', cursive;
        padding: 20px;
        font-style: italic;
        color: #666;
        text-align: left;
        letter-spacing: 1px;
        caption-side: top;
    }

    #customers {
        font-family: Arial, Helvetica, sans-serif;
        border-collapse: collapse;
        width: 100%;
    }

        #customers td, #customers th {
            border: 1px solid #ddd;
            padding: 8px;
        }

        #customers tr:nth-child(even) {
            background-color: #f2f2f2;
        }

        #customers tr:hover {
            background-color: #ddd;
        }

        #customers th {
            padding-top: 12px;
            padding-bottom: 12px;
            text-align: left;
            background-color: #4CAF50;
            color: white;
        }

    fieldset {
        margin-top: 20px;
        font-family: sans-serif;
        border: 5px solid #1F497D;
        background: #ddd;
        border-radius: 5px;
        padding: 15px;
    }

        fieldset legend {
            background: #1F497D;
            color: #fff;
            padding: 5px 10px;
            font-size: 32px;
            border-radius: 5px;
            box-shadow: 0 0 0 5px #ddd;
            width: 450px;
        }
</style>

Hotel/Views/Order/Reservation.cshtml
@model Hotel.Models.Order.OrderViewModel

<div class="container">
    <form asp-action="CompleteReservation" method="post">
        <div asp-validation-summary="ModelOnly"></div>
        <br />
        <div>
            <input type="checkbox" id="editinfo" onclick="agreeForm(this.form)" value="true" name="editinfo">
            <label for="editinfo">Оставить личные данные без изменений</label>
        </div>

        <fieldset id="infofieldest">
            <div>
                <label asp-for="FirstName"></label><br />
                <input asp-for="FirstName" />
                <span asp-validation-for="FirstName"></span>
            </div>
            <div>
                <label asp-for="LastName"></label><br />
                <input asp-for="LastName" />
                <span asp-validation-for="LastName"></span>
            </div>
            <div>
                <label asp-for="Patronymic"></label><br />
                <input asp-for="Patronymic" />
                <span asp-validation-for="Patronymic"></span>
            </div>
            <div>
                <label asp-for="PhoneNumber"></label><br />
                <input asp-for="PhoneNumber" />
                <span asp-validation-for="PhoneNumber"></span>
            </div>
        </fieldset>

        <label asp-for="FullPrice">Итоговая цена на @Model.Days сут.</label><br />
        <input type="number" asp-for="FullPrice" disabled />
        <input type="hidden" asp-for="FullPrice" />
        <input type="hidden" asp-for="Days" />
        <input type="hidden" asp-for="RoomId" />
        <input type="hidden" asp-for="CheckInTime" />
        <input type="hidden" asp-for="CheckOutTime" />

        <div style="margin-top:20px;">
            <input class="btn btn-success" type="submit" value="Забронировать" />
        </div>
    </form>
</div>


@section Scripts
{
    <script language="JavaScript">
        function agreeForm(f) {
            if (f.editinfo.checked) {
                document.getElementById("infofieldest").disabled = true;
            }
            else {
                document.getElementById("infofieldest").disabled = false;
            }
        }

    </script>
}

<style>
    input {
        padding: 10px;
        border-radius: 10px;
        box-shadow: 0 0 15px 4px rgba(0,0,0,0.06);
    }

    body {
        background: url(../img/banner2.jpg);
    }
</style>

Hotel/Views/Order/ReservationInfo.cshtml
@model Hotel.Models.Order.ReservationInfoViewModel

<head>
    <link rel="stylesheet" href="~/css/calendar.css" />
</head>

@{
    string returnUrl = Context.Request.Path.ToString() + Context.Request.QueryString.ToString();
}
<div class="container">
    @if (TempData["alert"] != null)
    {
        <div class="alert">
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span>
            <strong>Ошибка!</strong> @TempData["alert"]
        </div>
    }

    <form asp-action="Reservation" method="post">
        <br />
        <div class="calendars">
            <div class="tablefirst">
                <table class="table-select js-table-select">
                    <thead>
                        <tr>
                            <th class="month" colspan="7">@ViewData["NameMonth"]</th>
                        </tr>
                        <tr class="g">
                            <th>Пн</th>
                            <th>Вт</th>
                            <th>Ср</th>
                            <th>Чт</th>
                            <th>Пт</th>
                            <th>Сб</th>
                            <th>Вс</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Convert.ToInt32(ViewData["WeeksContFirstMonth"]); i++)
                        {
                            <tr>
                                @for (int x = 0; x < 7; x++)
                                {
                                    @if (Model.FirstMonth.Peek().Date < DateTime.Now || Model.AllOlders.Contains(Model.FirstMonth.Peek().Date))
                                    {
                                        <td class="date_disabled" data-date="@Model.FirstMonth.Peek().Date">
                                            @Model.FirstMonth.Dequeue().Day
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="date_enabled" data-date="@Model.FirstMonth.Peek().Date">
                                            @Model.FirstMonth.Dequeue().Day
                                        </td>

                                    }
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>

            <div class="tablesecond">
                <table class="table-select js-table-select">
                    <thead>
                        <tr>
                            <th class="month" colspan="7">@ViewData["NameNextMonth"]</th>
                        </tr>
                        <tr class="g">
                            <th>Пн</th>
                            <th>Вт</th>
                            <th>Ср</th>
                            <th>Чт</th>
                            <th>Пт</th>
                            <th>Сб</th>
                            <th>Вс</th>
                        </tr>
                    </thead>
                    <tbody>
                        @for (int i = 0; i < Convert.ToInt32(ViewData["WeeksContSecondMonth"]); i++)
                        {
                            <tr>
                                @for (int x = 0; x < 7; x++)
                                {
                                    @if (Model.AllOlders.Contains(Model.SecondtMonth.Peek().Date))
                                    {
                                        <td class="date_disabled" data-date="@Model.SecondtMonth.Peek().Date">
                                            @Model.SecondtMonth.Dequeue().Day
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="date_enabled" data-date="@Model.SecondtMonth.Peek().Date">
                                            @Model.SecondtMonth.Dequeue().Day
                                        </td>
                                    }
                                }
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>

        <input type="hidden" asp-for="RoomId" value="@Model.RoomId" />
        <input type="hidden" asp-for="InTime" id="InTime" />
        <input type="hidden" asp-for="OutTime" id="OutTime" />
        <input type="hidden" name="returnUrl" value="@returnUrl" />
        <input class="btn btn-outline-success" type="submit" value="Продолжить" />
    </form>

    <div class="roominfo">
        <h3 class="roomname">Выбранна комната: @Model.Room.RoomCategory.Name</h3>
        <p class="roomprice">Цена: @Model.Room.RoomCategory.Price</p>
    </div>
</div>
<script src="~/js/calendarScript.js"></script>