Hotel/Models/Order/AllOrdersViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Order
{
    public class AllOrdersViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public bool Buyed { get; set; }
        public int RoomId { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public Room Room { get; set; }
        public User User { get; set; }
        public Statuses Statuses { get; set; }
    }
}

Hotel/Models/Reception/AddEmployeeViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Reception
{
    public class AddEmployeeViewModel
    {
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public DateTime Birhrday { get; set; }
        public string Phone { get; set; }
        public int PostId { get; set; }
    }
}

Hotel/Models/Reception/AllOrdersHistoryViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Reception
{
    public class AllOrdersHistoryViewModel
    {
        public int Id { get; set; }
        public int FullPrice { get; set; }
        public DateTime OrderTime { get; set; }
        public DateTime CheckInTime { get; set; }
        public DateTime CheckOutTime { get; set; }
        public Room Room { get; set; }
        public User User { get; set; }
        public Statuses Statuses { get; set; }
    }
}

Hotel/Models/Reception/EditEmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Reception
{
    public class EditEmployeeViewModel
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public DateTime Birhrday { get; set; }
        public string Phone { get; set; }
        public int PostId { get; set; }
    }
}

Hotel/Models/Reception/EmployeeListViewModel.cs
using Hotel.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Models.Reception
{
    public class EmployeeListViewModel
    {
        public int Id { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Patronymic { get; set; }
        public DateTime Birhrday { get; set; }
        public string Phone { get; set; }
        public Post Post { get; set; }
    }
}

Hotel/Controllers/ReceptionController.cs
using AutoMapper;
using AutoMapper.QueryableExtensions;
using Hotel.Data.Interface;
using Hotel.Entities;
using Hotel.Models.Order;
using Hotel.Models.Reception;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hotel.Controllers
{
    [Authorize(Roles = "reception")]
    public class ReceptionController : Controller
    {
        private readonly UserManager<User> _userManager;
        private readonly IRepository<Employee> _repositoryemployee;
        private readonly IRepository<Post> _repositoryPost;
        private readonly IRepository<OrderHistory> _historyRepository;
        private readonly IRepository<Order> _orderRepository;
        private readonly IOrderRepository _repository;
        private readonly IMapper mapper;
        public ReceptionController(IRepository<Employee> repositoryemployee,
            IRepository<Post> repositoryPost, IMapper mapper, UserManager<User> userManager,
            IRepository<OrderHistory> historyRepository, IRepository<Order> orderRepository, IOrderRepository repository)
        {
            _repositoryemployee = repositoryemployee;
            _repositoryPost = repositoryPost;
            this.mapper = mapper;
            _userManager = userManager;
            _historyRepository = historyRepository;
            _orderRepository = orderRepository;
            _repository = repository;
        }

        public async Task<IActionResult> AllEmployees()
        {
            var allEmployee = await _repositoryemployee.GetAll()
                .Include(x => x.Post)
                .ProjectTo<EmployeeListViewModel>(mapper.ConfigurationProvider)
                .OrderBy(x => x.Id)
                .ToListAsync();

            return View(allEmployee);
        }

        public async Task<IActionResult> AddEmployee()
        {
            var allpost = await _repositoryPost.GetAll().ToListAsync();
            ViewBag.Post = new SelectList(allpost, "Id", "PostName");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEmployee(AddEmployeeViewModel model)
        {
            var employee = new Employee
            {
                LastName = model.LastName,
                FirstName = model.FirstName,
                Patronymic = model.Patronymic,
                Birhrday = model.Birhrday,
                Phone = model.Phone,
                PostId = model.PostId
            };

            await _repositoryemployee.AddAsync(employee);

            return RedirectToAction("AllEmployees");
        }

        public async Task<IActionResult> DeleteEmployee(int id)
        {
            var employee = await _repositoryemployee.GetByIdAsync(id);
            await _repositoryemployee.RemoveAsync(employee);

            return RedirectToAction("AllEmployees");
        }

        public async Task<IActionResult> EditEmployee(int id)
        {
            ViewBag.Post = new SelectList(await _repositoryPost.GetAll().ToListAsync(), "Id", "PostName");

            var employee = await _repositoryemployee.GetByIdAsync(id);
            var modelemployee = new EditEmployeeViewModel
            {
                Id = employee.Id,
                Birhrday = employee.Birhrday,
                FirstName = employee.FirstName,
                LastName = employee.LastName,
                Patronymic = employee.Patronymic,
                Phone = employee.Phone,
                PostId = employee.PostId
            };

            return View(modelemployee);
        }

        [HttpPost]
        public async Task<IActionResult> EditEmployee(EditEmployeeViewModel model)
        {
            var employee = await _repositoryemployee.GetAll()
                .Where(x => x.Id == model.Id)
                .FirstOrDefaultAsync();
            if (employee != null)
            {
                employee.LastName = model.LastName;
                employee.FirstName = model.FirstName;
                employee.Patronymic = model.Patronymic;
                employee.Birhrday = model.Birhrday;
                employee.Phone = model.Phone;
                employee.PostId = model.PostId;
                await _repositoryemployee.SaveAsync();
            }

            await _repositoryemployee.UpdateAsync(employee);

            return RedirectToAction("AllEmployees");
        }

        public async Task<IActionResult> DeleteSelectedEmployeers(List<int> employersId)
        {
            foreach (var id in employersId)
            {
                var employee = await _repositoryemployee.GetByIdAsync(id);
                if (employee != null)
                {
                    await _repositoryemployee.RemoveAsync(employee);
                }
            }
            return RedirectToAction("AllEmployees");
        }

        public async Task<IActionResult> AllOrdersHistory(string sortorders, string search, string personalInfo, DateTime dateTime)
        {
            var order = _historyRepository.GetAll();

            switch (sortorders)
            {
                case "checkInUp": order = order.OrderBy(x => x.CheckInTime); break;
                case "checkOutUp": order = order.OrderBy(x => x.CheckOutTime); break;
                case "checkInDown": order = order.OrderByDescending(x => x.CheckInTime); break;
                case "checkOutDown": order = order.OrderByDescending(x => x.CheckOutTime); break;
            }

            switch (search)
            {
                case "searchIn": order = order.Where(x => x.CheckInTime == dateTime); break;
                case "searchOut": order = order.Where(y => y.CheckOutTime == dateTime); break;
                case "searchPrice": order = order.Where(z => z.FullPrice == Convert.ToInt32(personalInfo)); break;
            }

            if (search != null)
            {
                var allOrdersUser = order
                 .Include(x => x.User);

                switch (search)
                {
                    case "searchLastName": order = allOrdersUser.Where(x => x.User.LastName == personalInfo); break;
                    case "searchName": order = allOrdersUser.Where(x => x.User.FirstName == personalInfo); break;
                    case "searchPatr": order = allOrdersUser.Where(x => x.User.Patronymic == personalInfo); break;
                }
            }

            var allOrders = await order
                .Include(x => x.User)
                .Include(x => x.Room.RoomCategory)
            .ProjectTo<AllOrdersHistoryViewModel>(mapper.ConfigurationProvider)
            .ToListAsync();

            return View(allOrders);
        }

        public async Task<IActionResult> AllOrders(string sortorders, string search, string info, DateTime dateTime, string keygive)
        {
            var order = _orderRepository.GetAll();

            switch (sortorders)
            {
                case "checkInUp": order = order.OrderBy(x => x.CheckInTime); break;
                case "checkOutUp": order = order.OrderBy(x => x.CheckOutTime); break;
                case "checkInDown": order = order.OrderByDescending(x => x.CheckInTime); break;
                case "checkOutDown": order = order.OrderByDescending(x => x.CheckOutTime); break;
            }

            switch (search)
            {
                case "searchIn": order = order.Where(x => x.CheckInTime == dateTime); break;
                case "searchOut": order = order.Where(y => y.CheckOutTime == dateTime); break;
                case "searchPrice": order = order.Where(z => z.FullPrice == Convert.ToInt32(info)); break;
                case "searchLastName": order = order.Where(x => x.LastName == info); break;
                case "searchName": order = order.Where(x => x.FirstName == info); break;
                case "searchPatr": order = order.Where(x => x.Patronymic == info); break;
                case "searchPhone": order = order.Where(x => x.PhoneNumber == info); break;
                case "searchMail": order = order.Where(x => x.Email == info); break;
            }

            if (search == "searchStatus")
            {
                var statusroom = order.Include(k => k.Room).Include(x => x.Room.RoomCategory);
                switch (keygive)
                {
                    case "give": order = statusroom.Where(k => k.Statuses == Statuses.Given); break;
                    case "notgive": order = statusroom.Where(k => k.Statuses == Statuses.NotGiven); break;
                }
            }

            if(search == "searchRoom")
            {
                var roomname = order.Include(x => x.Room.RoomCategory).Include(k => k.Room);

                order = roomname.Where(f=> f.Room.RoomCategory.Name == info);
            }

            var allorders = await order
                   .Include(x => x.Room.RoomCategory)
                   .ProjectTo<AllOrdersViewModel>(mapper.ConfigurationProvider)
                   .ToListAsync();

            return View(allorders);
        }

        public async Task<IActionResult> Key(int id)
        {
            await _repository.SwitchKeyAsync(id);

            return RedirectToAction("AllOrders");
        }

        public async Task<IActionResult> Buyed(int id)
        {
            await _repository.ConfirmBuy(id);

            return RedirectToAction("AllOrders");
        }

        public async Task<IActionResult> DeleteOrder(int orderId)
        {
            var keystatus = await _repository.GetKeyStatusAsync(orderId);

            if (keystatus == Statuses.Given)
            {
                return RedirectToAction("AllOrders");
            }

            var order = await _orderRepository.GetByIdAsync(orderId);
            await _orderRepository.RemoveAsync(order);

            return RedirectToAction("AllOrders");

Hotel/Views/Reception/AddEmployee.cshtml
@model Hotel.Models.Reception.AddEmployeeViewModel

<div class="container">
    <form asp-action="AddEmployee" asp-controller="Reception" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div>
            <label asp-for="LastName">Фамилия</label><br />
            <input type="text" asp-for="LastName" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="FirstName">Имя</label><br />
            <input type="text" asp-for="FirstName" />
            <span asp-validation-for="FirstName"></span>
        </div>
        <div>
            <label asp-for="Patronymic">Отчество</label><br />
            <input type="text" asp-for="Patronymic" />
            <span asp-validation-for="Patronymic" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Birhrday">Дата рождения</label><br />
            <input asp-for="Birhrday" />
            <span asp-validation-for="Birhrday" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="Phone">Номер телефона</label><br />
            <input type="text" asp-for="Phone" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
        <div>
            <label asp-for="PostId">Выберите категорию</label><br />
            <select class="select-css" asp-for="PostId" asp-items="ViewBag.Post"></select>
        </div>
        <div class="form-group">
            <input style="margin-top: 20px;" type="submit" value="Добавить" class="btn btn-outline-dark" />
        </div>
    </form>
    <a style="margin-top: 20px;" asp-action="AllEmployees" asp-controller="Reception">Назад</a>
</div>

<style>
    body {
        background: url(../img/banner2.jpg);
    }

    input {
        padding: 10px;
        border-radius: 10px;
        box-shadow: 0 0 15px 4px rgba(0,0,0,0.06);
    }

    .select-css {
        display: block;
        font-size: 16px;
        font-family: sans-serif;
        font-weight: 700;
        color: #444;
        line-height: 1.3;
        padding: .6em 1.4em .5em .8em;
        display: inline-block;
        max-width: 100%;
        box-sizing: border-box;
        margin: 0;
        border: 1px solid #aaa;
        box-shadow: 0 1px 0 1px rgba(0,0,0,.04);
        border-radius: .5em;
        -moz-appearance: none;
        -webkit-appearance: none;
        background-color: #fff;
        background-image: url('data:image/svg+xml;charset=US-ASCII,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22292.4%22%20height%3D%22292.4%22%3E%3Cpath%20fill%3D%22%23007CB2%22%20d%3D%22M287%2069.4a17.6%2017.6%200%200%200-13-5.4H18.4c-5%200-9.3%201.8-12.9%205.4A17.6%2017.6%200%200%200%200%2082.2c0%205%201.8%209.3%205.4%2012.9l128%20127.9c3.6%203.6%207.8%205.4%2012.8%205.4s9.2-1.8%2012.8-5.4L287%2095c3.5-3.5%205.4-7.8%205.4-12.8%200-5-1.9-9.2-5.5-12.8z%22%2F%3E%3C%2Fsvg%3E'), linear-gradient(to bottom, #ffffff 0%,#e5e5e5 100%);
        background-repeat: no-repeat, repeat;
        background-position: right .7em top 50%, 0 0;
        background-size: .65em auto, 100%;
    }
</style>

Hotel/Views/Reception/AllEmployees.cshtml
@model IEnumerable<Hotel.Models.Reception.EmployeeListViewModel>
<head>
    <title>Сотрудники</title>
</head>

<div class="container">
    <form>
        <div class="buttons">
            <input class="btn btn-info" type="submit" asp-action="DeleteSelectedEmployeers" value="Удалить выбранных сотрудников" />
            <a class="btn btn-success" asp-action="AddEmployee" asp-controller="Reception">Добавить сотрудника</a>
        </div>

        <table class="table" id="infoTable">
            <tr>
                <th><input type="checkbox" onClick="toggle(this)" /> Выбрать все<br /></th>
                <th>
                    Фамилия
                    <input style="max-width: 100px;" type="text" id="inputsurname" onkeyup="Filter()">
                </th>
                <th>Имя</th>
                <th>Отчество</th>
                <th>Телефон</th>
                <th>Должность</th>
                <th>Зарплата</th>
                <th></th>
            </tr>
            @foreach (var employee in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="employersId" value="@employee.Id">
                    </td>
                    <td>@employee.LastName</td>
                    <td>@employee.FirstName</td>
                    <td>@employee.Patronymic</td>
                    <td>@employee.Phone</td>
                    <td>@employee.Post.PostName</td>
                    <td>@employee.Post.Salary</td>
                    <td>
                        <a class="btn btn-success" asp-action="EditEmployee" asp-route-id="@employee.Id">Изменить</a>
                        <a class="btn btn-danger" asp-action="DeleteEmployee" asp-route-id="@employee.Id">Удалить</a>
                    </td>
                </tr>
            }
        </table>
    </form>
</div>

@section Scripts
{
    <script language="JavaScript">
        function toggle(source) {
            checkboxes = document.getElementsByName('employersId');
            for (var i = 0, n = checkboxes.length; i < n; i++) {
                checkboxes[i].checked = source.checked;
            }
        }

        function Filter() {
            input = document.getElementById("inputsurname");
            filter = input.value.toUpperCase();
            table = document.getElementById("infoTable");
            tr = table.getElementsByTagName("tr");

            for (i = 0; i < tr.length; i++) {
                td = tr[i].getElementsByTagName("td")[1];
                if (td) {
                    if (td.innerHTML.toUpperCase().indexOf(filter) > -1) {
                        tr[i].style.display = "";
                    } else {
                        tr[i].style.display = "none";
                    }
                }
            }
        }
    </script>
}

<style>
    body {
        background: url(../img/banner2.jpg);
    }

    .table {
        width: 100%;
        margin-bottom: 20px;
        border: 15px solid #F2F8F8;
        border-top: 5px solid #F2F8F8;
        border-collapse: collapse;
    }

        .table th {
            font-weight: bold;
            padding: 5px;
            background: #F2F8F8;
            border: none;
            border-bottom: 5px solid #F2F8F8;
        }

        .table td {
            padding: 5px;
            border: none;
            border-bottom: 5px solid #F2F8F8;
        }

    .buttons {
        margin-top: 20px;
        margin-bottom: 20px;
    }
</style>

Hotel/Views/Reception/AllOrders.cshtml
@model IEnumerable<Hotel.Models.Order.AllOrdersViewModel>
@using Hotel.Entities;

<div class="container">
    <a asp-controller="Reception" asp-action="AllOrdersHistory">История всех заказов</a>

    <form asp-action="AllOrders" method="get">
        <div class="filter-group">
            <select class="select" name="sortorders">
                <option selected="selected" value="0" disabled="disabled">Сортировать:</option>
                <optgroup label="По возрастанию">
                    <option value="checkInUp">По дате заезда</option>
                    <option value="checkOutUp">По дате выезда</option>
                </optgroup>
                <optgroup label="По убыванию">
                    <option value="checkInDown">По дате заезда</option>
                    <option value="checkOutDown">По дате выезда</option>
                </optgroup>
            </select>
            <input class="btn btn-success" type="submit" value="Сортировать" />
            <a class="btn btn-danger" asp-action="AllOrders">Сброс</a>
        </div>
    </form>

    <form asp-action="AllOrders" method="get">
        <div class="search-group">
            <div class="form-group">
                <select class="select" name="search" id="search">
                    <option selected="selected" value="0" disabled="disabled">Поиск:</option>
                    <optgroup label="Личные данные">
                        <option value="searchLastName">Фамилия</option>
                        <option value="searchName">Имя</option>
                        <option value="searchPatr">Отчество</option>
                        <option value="searchPhone">Телефон</option>
                        <option value="searchMail">Mail</option>
                    </optgroup>
                    <optgroup label="Дата">
                        <option value="searchIn">Заезд</option>
                        <option value="searchOut">Выезд</option>
                    </optgroup>
                    <optgroup label="Комната">
                        <option value="searchRoom">Вид</option>
                        <option value="searchStatus">Статус</option>
                    </optgroup>
                </select>
            </div>
            <div class="form-group" id="infodiv">
                <input type="text" size="15" name="info" id="info" />
            </div>
            <div class="form-group">
                <input type="date" name="dateTime" id="dateTime" />
            </div>

            <div id="radiodiv">
                <div class="form-group">
                    <input type="radio" value="give" name="keygive" id="give" />
                    <label for="give">Ключ выдан</label>
                </div>
                <div class="form-group">
                    <input type="radio" value="notgive" name="keygive" id="notgive" />
                    <label for="notgive">Ключ не выдан</label>
                </div>
            </div>

            <input class="btn btn-success" type="submit" value="Поиск" />
        </div>
    </form>
    <br />
    <table class="table">
        <tr>
            <th>Комната</th>
            <th>Фамилия</th>
            <th>Имя</th>
            <th>Отчество</th>
            <th>Номер</th>
            <th>Почта</th>
            <th>Дата заезда</th>
            <th>Дата выезда</th>
            <th>Статус</th>
            <th></th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {

            <tr>
                <td>
                    @item.Room.RoomCategory.Name
                </td>
                <td>
                    @item.FirstName
                </td>
                <td>
                    @item.LastName
                </td>
                <td>
                    @item.Patronymic
                </td>
                <td>
                    @item.PhoneNumber
                </td>
                <td>
                    @item.Email
                </td>
                <td>
                    @item.CheckInTime
                </td>
                <td>
                    @item.CheckOutTime
                </td>
                @if (item.Statuses == Statuses.Expired)
                {
                    <td>
                        <p>Просрочено</p>
                    </td>
                }
                else if (item.Buyed == false)
                {
                    <td>
                        <a class="btn btn-warning" asp-controller="Reception" asp-action="Buyed" asp-route-id="@item.Id">Подтверждение оплаты</a>
                    </td>
                }
                else
                {
                    @if (item.Statuses == Statuses.NotGiven)
                    {
                        <td>
                            <p>Не выдан</p>
                        </td>
                        <td>
                            <a class="btn btn-success" asp-controller="Reception" asp-action="Key" asp-route-id="@item.Id">Выдать</a>
                        </td>
                    }
                    else if (item.Statuses == Statuses.Given)
                    {
                        <td>
                            <p>Выдан</p>
                        </td>
                        <td>
                            <a class="btn btn-success" asp-controller="Reception" asp-action="Key" asp-route-id="@item.Id">Возврат</a>
                        </td>
                    }
                    else if (item.Statuses == Statuses.Completed)
                    {
                        <td>
                            <p>Возвращён</p>
                        </td>
                    }
                }
                <td>
                    <a class="btn btn-danger" asp-controller="Reception" asp-action="DeleteOrder" asp-route-orderId="@item.Id">Удалить</a>
                </td>
            </tr>
        }
    </table>
</div>

<style>
    body {
        background: url(../img/banner2.jpg);
    }

    table {
        font-family: "Lucida Sans Unicode", "Lucida Grande", Sans-Serif;
        font-size: 15px;
        border-collapse: collapse;
        text-align: center;
    }

    th, td:first-child {
        background: #AFCDE7;
        color: white;
        padding: 10px 20px;
    }

    th, td {
        border-style: solid;
        border-width: 0 1px 1px 0;
        border-color: white;
    }

    td {
        background: #D8E6F3;
    }

        th:first-child, td:first-child {
            text-align: left;
        }

    .search-group {
        position: fixed;
        left: 10px;
    }
</style>

@section scripts{
    <script>
        document.getElementById("infodiv").style.display = 'none';
        document.getElementById("dateTime").style.display = 'none';
        document.getElementById("radiodiv").style.display = 'none';

        $('#search').click(function () {
            var n = document.getElementById("search").options.selectedIndex;
            var txt = document.getElementById("search").options[n].value;
            if (txt == "searchLastName" || txt == "searchName" || txt == "searchPatr" || txt == "searchPhone" || txt == "searchMail" || txt == "searchRoom") {
                document.getElementById("infodiv").style.display = 'block';
            }
            else {
                document.getElementById("infodiv").style.display = 'none';
            }

            if (txt == "searchIn" || txt == "searchOut") {
                document.getElementById("dateTime").style.display = 'block';
            }
            else {
                document.getElementById("dateTime").style.display = 'none';
            }

            if (txt == "searchStatus") {
                document.getElementById("radiodiv").style.display = 'block';
            }
            else {
                document.getElementById("radiodiv").style.display = 'none';
            }
        })


    </script>
}

Hotel/Views/Reception/EditEmployee.cshtml
@model Hotel.Models.Reception.EditEmployeeViewModel

<div class="container">
    <form asp-action="EditEmployee" method="post">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="LastName" class="control-label">Фамилия</label>
            <input type="text" asp-for="LastName" class="form-control" />
            <span asp-validation-for="LastName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="FirstName" class="control-label">Имя</label>
            <input type="text" asp-for="FirstName" class="form-control" />
            <span asp-validation-for="FirstName" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Patronymic" class="control-label">Отчество</label>
            <input type="text" asp-for="Patronymic" class="form-control" />
            <span asp-validation-for="Patronymic" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Birhrday" class="control-label">Дата рождения</label>
            <input asp-for="Birhrday" class="form-control" />
            <span asp-validation-for="Birhrday" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="Phone" class="control-label">Номер телефона</label>
            <input type="text" asp-for="Phone" class="form-control" />
            <span asp-validation-for="Phone" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="PostId">Выберите категорию</label>
            <select asp-for="PostId" asp-items="ViewBag.Post"></select>
        </div>
        <div class="form-group">
            <input type="hidden" asp-for="Id" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Именить" class="btn btn-info" />
        </div>
    </form>
    <a asp-action="AllEmployees" asp-controller="Reception">Назад</a>
</div>
<style>
    body {
        background: url(../img/banner2.jpg);
    }
</style>